D_interval: 1
audio_samples: 10
aux_zero: false
auxiliary_dim: 32
auxiliary_sample_rate: 32
auxiliary_type: lstm_last
batch_size: 8
beta1: 0.5
checkpoint_path: ''
continue_train: false
cudnn_benchmark: false
cudnn_enabled: true
decoder_conv_dim: 1024
dist_backend: nccl
dist_url: tcp://localhost:54321
dynamic_loss_scaling: true
encoder_embedding_dim: 2048
encoder_kernel_size: 5
encoder_n_convolutions: 3
encoder_n_lstm: 2
epoch_count: 0
epochs: 1000
exclude_dirs:
- ckpt
- data
flow_feature_dir: data/features/dog/feature_flow_bninception_dim1024_21.5fps
grad_clip_thresh: 1.0
lambda_Oriloss: 10000.0
lambda_Silenceloss: 0
loss_type: MSE
lr: 0.0002
mel_dir: data/features/dog/melspec_10s_22050hz
mel_samples: 860
mode_input: ''
n_mel_channels: 80
niter: 100
num_epoch_save: 10
postnet_embedding_dim: 512
postnet_kernel_size: 5
postnet_n_convolutions: 5
random_z_dim: 512
rgb_feature_dir: data/features/dog/feature_rgb_bninception_dim1024_21.5fps
save_dir: ckpt/dog
seed: 123
test_files: filelists/dog_test.txt
training_files: filelists/dog_train.txt
video_samples: 215
visual_dim: 2048
weight_decay: 1.0e-06
wo_G_GAN: false
